### ISSUE TITLE
Tweets not displaying

### ISSUE THREAD

**Issue by keybits** [toshimaru/RailsTwitterClone#684]
Cloned project and running locally. Can sign in and write tweets, but they don't display:

![image](https://user-images.githubusercontent.com/809823/74748017-bdecb980-525f-11ea-9236-0e9fc60354b1.png)

Haven't tried to debug yet. Thanks for your work providing this project :-)

**Comment by toshimaru** [comment]
It works for me. Please check your browser setting. :)

![Feb-19-2020 00-27-13](https://user-images.githubusercontent.com/803398/74750149-9e30b200-52ae-11ea-9f57-02a00cbb9c1e.gif)
